version: "2"

linters:
  enable:
    - bodyclose
    - noctx
    - rowserrcheck
    - goprintffuncname
    - misspell
    - nolintlint
    - staticcheck
    - whitespace
    - tparallel
    - sqlclosecheck
    - lll
  disable:
    - errcheck
    - ineffassign
    - unused

linters-settings:
  lll:
    line-length: 120

