version: "2"

linters:
  enable:
    - bodyclose
    - noctx
    - rowserrcheck
    - goprintffuncname
    - misspell
    - nolintlint
    - staticcheck
    - whitespace
    - tparallel
    - sqlclosecheck
  disable:
    - errcheck
    - ineffassign
    - unused
