// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package bootstrap

import (
	"github.com/google/wire"
)

// Injectors from wire.go:

// InitializeApp creates and initializes the entire application
// This function will be replaced by generated wire_gen.go
func InitializeApp(opts AppOptions) *App {
	manager := provideConfigManager()
	client := provideHTTPClient()
	authenticator := provideAuthenticator(client)
	authServicer := provideAuthService(authenticator)
	libraryServicer := provideLibraryService()
	playbackService := providePlaybackService()
	playbackServicer := providePlaybackServicer(playbackService)
	appServices := provideAppServices(authServicer, libraryServicer, playbackServicer)
	coordinator := provideCoordinator(appServices, manager, opts)
	router := provideRouter(manager, coordinator, authServicer)
	keyMap := provideKeyMap()
	pageFactoryFn := providePageFactory(coordinator, authServicer, manager)
	appModel := provideAppModel(router, coordinator, authServicer, manager, keyMap, pageFactoryFn)
	orchestrator := provideOrchestrator(coordinator, playbackService)
	mediaControlWrapper := provideMediaControlWrapper(playbackService, orchestrator, coordinator)
	app := provideApp(appModel, orchestrator, playbackService, manager, mediaControlWrapper)
	return app
}

// wire.go:

// Wire set for all providers
var appSet = wire.NewSet(
	provideHTTPClient,
	provideAuthenticator,
	provideAuthService,
	provideLibraryService,
	providePlaybackService,
	providePlaybackServicer,
	provideAppServices,
	provideConfigManager,
	provideCoordinator,
	provideOrchestrator,
	provideKeyMap,
	provideRouter,
	providePageFactory,
	provideAppModel,
	provideMediaControlWrapper,
	provideApp,
)
